name: Update Blog Content

on:
  repository_dispatch:
    types: [blog_content_update]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Git user
        run: |
          git config --global user.email "jerry@semurai.se"
          git config --global user.name "JerrySem"

      - name: Update blog-content submodule
        run: |
          git submodule update --remote blog-content
          git add blog-content
          git commit -m "Update blog-content submodule" || echo "No changes to commit"
          git push

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/johansemurai/semurai-dev-blog.git

      - name: Build and Deploy
        run: |
          npm install
          npm run build
          npm run deploy
